name: Deployment

on:
  push:
    tags:
      - 'v\d+\.\d+\.\d+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Derive Tag Name And Populate version.ts
        id: derive_tag
        run: |
          echo well hello there
          TAG=$(basename "${{ github.ref }}")
          echo dt $TAG
  approve1:
    runs-on: ubuntu-latest
    environment: Production
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      - name: Derive Tag Name And Populate version.ts
        id: derive_tag2
        run: |
          TAG=$(basename "${{ github.ref }}")
          echo dt2 $TAG
  approve2:
    runs-on: ubuntu-latest
    environment: Production
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      - name: Derive Tag Name And Populate version.ts
        id: derive_tag2
        run: |
          TAG=$(basename "${{ github.ref }}")
          echo dt2 $TAG
  confirm:
    runs-on: ubuntu-latest
    environment: Production
    needs:
     - approve1
     - approve2
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      - name: Derive Tag Name And Populate version.ts
        id: derive_tag2
        run: |
          TAG=$(basename "${{ github.ref }}")
          echo dt2 $TAG
