name: Deployment

on:
  push:
    tags:
      - 'v\d+\.\d+\.\d+'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
